// Real, recognizable brand/platform icons from react-icons (simple-icons + font-awesome sets).
// Falls back to a plain universal glyph only for concepts that have no official logo
// (e.g. "REST API", "JWT", "OAuth" — these are protocols/specs, not products).
import {
  SiPython, SiJavascript, SiTypescript, SiHtml5,
  SiSpringboot, SiHibernate, SiNodedotjs, SiFastapi,
  SiReact, SiBootstrap, SiJquery, SiGraphql, SiJson, SiXml,
  SiPostgresql, SiMysql, SiRedis, SiApachesolr, SiApachekafka, SiRabbitmq,
  SiDocker, SiKubernetes, SiGit, SiGitlab, SiApachemaven, SiGradle,
  SiJenkins, SiTeamcity, SiAnsible, SiJsonwebtokens, SiVault,
  SiLangchain, SiGithubcopilot, SiSelenium, SiDatadog, SiJira,
  SiConfluence, SiIntellijidea, SiEclipseide, SiPostman, SiGithub,
  SiLeetcode, SiGooglecloud, SiAmericanexpress,
} from "react-icons/si";
import {
  FaJava, FaAws, FaLinkedin, FaCss3Alt, FaDatabase, FaNetworkWired,
  FaShieldHalved, FaKey, FaLock, FaCertificate, FaBrain, FaComments,
  FaCircleNodes, FaEnvelopesBulk, FaGraduationCap, FaFlag, FaHandHoldingHeart,
  FaPlus, FaCircleCheck, FaEnvelope, FaPhone, FaThumbsUp, FaHandsClapping,
  FaBriefcase, FaArrowTrendUp, FaFlask, FaLayerGroup, FaDownload,
} from "react-icons/fa6";
import { TbBrandVscode } from "react-icons/tb";

const map = {
  java: FaJava,
  python: SiPython,
  javascript: SiJavascript,
  typescript: SiTypescript,
  html: SiHtml5,
  css: FaCss3Alt,
  springboot: SiSpringboot,
  hibernate: SiHibernate,
  nodejs: SiNodedotjs,
  fastapi: SiFastapi,
  react: SiReact,
  bootstrap: SiBootstrap,
  jquery: SiJquery,
  restapi: FaNetworkWired,
  graphql: SiGraphql,
  json: SiJson,
  xml: SiXml,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  jpa: FaDatabase,
  jdbc: FaDatabase,
  redis: SiRedis,
  solr: SiApachesolr,
  kafka: SiApachekafka,
  activemq: FaEnvelopesBulk,
  rabbitmq: SiRabbitmq,
  awss3: FaAws,
  awsecs: FaAws,
  awsec2: FaAws,
  gcp: SiGooglecloud,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  git: SiGit,
  gitlab: SiGitlab,
  maven: SiApachemaven,
  gradle: SiGradle,
  jenkins: SiJenkins,
  teamcity: SiTeamcity,
  ansible: SiAnsible,
  oauth: FaKey,
  jwt: SiJsonwebtokens,
  vault: SiVault,
  blackduck: FaShieldHalved,
  fortify: FaCertificate,
  llms: FaBrain,
  rag: FaCircleNodes,
  langchain: SiLangchain,
  langgraph: FaCircleNodes,
  promptengineering: FaComments,
  githubcopilot: SiGithubcopilot,
  selenium: SiSelenium,
  datadog: SiDatadog,
  jira: SiJira,
  confluence: SiConfluence,
  intellij: SiIntellijidea,
  vscode: TbBrandVscode,
  eclipse: SiEclipseide,
  postman: SiPostman,
  github: SiGithub,
  linkedin: FaLinkedin,
  leetcode: SiLeetcode,
  gradcap: FaGraduationCap,
  flag: FaFlag,
  hand: FaHandHoldingHeart,
  plus: FaPlus,
  check: FaCircleCheck,
  lock: FaLock,
  briefcase: FaBriefcase,
  growth: FaArrowTrendUp,
  research: FaFlask,
  associate: FaLayerGroup,
  email: FaEnvelope,
  phone: FaPhone,
  thumbsup: FaThumbsUp,
  highfive: FaHandsClapping,
  amex: SiAmericanexpress,
  download: FaDownload,
};

export default function TechIcon({ name, size = 15, ...rest }) {
  const Cmp = map[name] || FaCircleNodes;
  return <Cmp size={size} {...rest} />;
}
